-- MySQL Script generated by MySQL Workbench
-- Sun May  5 22:40:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdventas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdventas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdventas` DEFAULT CHARACTER SET utf8 ;
USE `bdventas` ;

-- -----------------------------------------------------
-- Table `bdventas`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdventas`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nom_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdventas`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdventas`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `idcategoria` INT NOT NULL,
  `nom_producto` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(5) NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idproducto`),
  UNIQUE INDEX `nom_producto_UNIQUE` (`nom_producto` ASC),
  INDEX `fk_producto_categoria_idx` (`idcategoria` ASC),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `bdventas`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdventas`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdventas`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nom_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdventas`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdventas`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `rol_idrol` INT NOT NULL,
  `nom_user` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `nom_user_UNIQUE` (`nom_user` ASC),
  INDEX `fk_usuario_rol1_idx` (`rol_idrol` ASC),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `bdventas`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdventas`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdventas`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdventas`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdventas`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `doc` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idventas`),
  INDEX `fk_ventas_usuario1_idx` (`idusuario` ASC),
  INDEX `fk_ventas_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_ventas_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bdventas`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `bdventas`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdventas`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdventas`.`detalle_venta` (
  `iddetalle_venta` INT NOT NULL AUTO_INCREMENT,
  `idventas` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `precio_venta` DECIMAL(5) NOT NULL,
  `cantidad_venta` INT NOT NULL,
  PRIMARY KEY (`iddetalle_venta`),
  INDEX `fk_detalle_venta_ventas1_idx` (`idventas` ASC),
  INDEX `fk_detalle_venta_producto1_idx` (`idproducto` ASC),
  CONSTRAINT `fk_detalle_venta_ventas1`
    FOREIGN KEY (`idventas`)
    REFERENCES `bdventas`.`ventas` (`idventas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_venta_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `bdventas`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
